server:
  port: 8081

spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spendsmart_expense
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

aws:
  region: ap-south-1
  endpoint-url: ${AWS_ENDPOINT_URL:http://localhost:4566}

management:
  endpoints:
    web:
      exposure:
        include: health,info
