server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spendsmart_expense}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:myverylonglocalsecretsigninkeyforjwt12345678}
  expiration: ${JWT_EXPIRATION:86400000}

aws:
  region: ${AWS_REGION:ap-south-1}
  endpoint-url: ${AWS_ENDPOINT_URL:http://localhost:4566}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:http://localhost:4566/000000000000/expense-events}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}