CREATE TABLE IF NOT EXISTS expenses (
    id UUID PRIMARY KEY,
    org_id UUID,
    user_id UUID,
    amount NUMERIC(14,2),
    currency CHAR(3),
    amount_base NUMERIC(14,2),
    base_currency CHAR(3),
    fx_rate NUMERIC(18,6),
    category_id UUID,
    category_confidence NUMERIC(5,4),
    merchant_name VARCHAR(255),
    merchant_vpa VARCHAR(255),
    payment_method VARCHAR(20),
    status VARCHAR(20) DEFAULT 'DRAFT',
    receipt_id UUID,
    project_id UUID,
    gstin_supplier VARCHAR(15),
    gst_amount NUMERIC(14,2),
    cgst NUMERIC(14,2),
    sgst NUMERIC(14,2),
    igst NUMERIC(14,2),
    hsn_sac_code VARCHAR(8),
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    notes TEXT,
    expense_date DATE NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
