-- Force-create SpendSmart demo users (admin/manager/employee)
-- Password for all: Password@123 (BCrypt cost 10 generated by pgcrypto)
-- Safe to run multiple times.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;

WITH
  deleted AS (
    DELETE FROM users
    WHERE email IN ('admin@spendsmart.in','manager@spendsmart.in','employee@spendsmart.in')
    RETURNING email
  ),
  existing_org AS (
    SELECT id
    FROM organizations
    WHERE name = 'SpendSmart Demo Org'
    LIMIT 1
  ),
  inserted_org AS (
    INSERT INTO organizations (name, plan, base_currency, state_code)
    SELECT 'SpendSmart Demo Org', 'business', 'INR', '27'
    WHERE NOT EXISTS (SELECT 1 FROM existing_org)
    RETURNING id
  ),
  org AS (
    SELECT id FROM inserted_org
    UNION ALL
    SELECT id FROM existing_org
    LIMIT 1
  ),
  pwd AS (
    SELECT crypt('Password@123', gen_salt('bf', 10)) AS password_hash
  )
INSERT INTO users (org_id, email, password_hash, role, default_currency)
SELECT
  org.id,
  u.email,
  pwd.password_hash,
  u.role,
  'INR'
FROM org
CROSS JOIN pwd
CROSS JOIN (
  VALUES
    ('admin@spendsmart.in', 'admin'),
    ('manager@spendsmart.in', 'manager'),
    ('employee@spendsmart.in', 'employee')
) AS u(email, role)
ON CONFLICT (email) DO UPDATE
SET
  org_id = EXCLUDED.org_id,
  password_hash = EXCLUDED.password_hash,
  role = EXCLUDED.role,
  default_currency = EXCLUDED.default_currency;

COMMIT;
