services:
  expense-service:
    build:
      context: ../services/expense-service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_OPEN_IN_VIEW: ${SPRING_JPA_OPEN_IN_VIEW}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_FLYWAY_ENABLED: ${SPRING_FLYWAY_ENABLED}
      SPRING_FLYWAY_LOCATIONS: ${SPRING_FLYWAY_LOCATIONS}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_SQS_QUEUE_URL: ${AWS_SQS_QUEUE_URL}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - localstack

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spendsmart_expense
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: spendsmart-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3
    environment:
      SERVICES: s3,sqs,sns,secretsmanager
      DEFAULT_REGION: ap-south-1
      AWS_DEFAULT_REGION: ap-south-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  localstack_data:
  elasticsearch_data:
